- hosts: all
  become: yes

  # AUCUN défaut ici, tout vient d'AWX
  vars:
    smtp_host: "{{ smtp_host }}"
    smtp_port: "{{ smtp_port }}"
    smtp_user: "{{ smtp_user }}"
    smtp_password: "{{ smtp_password }}"
    mail_to: "{{ mail_to }}"
    mail_from: "{{ mail_from }}"
    network_to_scan: "{{ network_to_scan }}"

  tasks:
    - name: Ensure nmap is installed
      ansible.builtin.apt:
        name: nmap
        state: present
        update_cache: yes

    - name: Run full TCP Nmap scan
      ansible.builtin.command: "nmap -p- -T4 {{ network_to_scan }}"
      register: scan_result

    - name: Save scan output to file
      ansible.builtin.copy:
        content: "{{ scan_result.stdout }}"
        dest: "/tmp/nmap_full_scan_{{ inventory_hostname }}.txt"

    - name: Send scan report by email
      ansible.builtin.mail:
        host: "{{ smtp_host }}"
        port: "{{ smtp_port }}"
        username: "{{ smtp_user }}"
        password: "{{ smtp_password }}"
        to: "{{ mail_to }}"
        from: "{{ mail_from }}"
        subject: "Nmap scan report - {{ inventory_hostname }}"
        body: |
          Machine : {{ inventory_hostname }}
          Réseau scanné : {{ network_to_scan }}

          ----------------------------
          Résultat Nmap :
          ----------------------------
          {{ scan_result.stdout }}
        secure: starttls
